-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 18:22:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sandcastle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sandcastle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sandcastle` DEFAULT CHARACTER SET utf8mb4 ;
USE `sandcastle` ;

-- -----------------------------------------------------
-- Table `sandcastle`.`sandcastle_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandcastle`.`sandcastle_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `status` INT UNSIGNED NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` BINARY(80) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandcastle`.`sandcastle_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandcastle`.`sandcastle_file` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `user_uuid` BINARY(16) NOT NULL,
  `object_uuid` BINARY(16) NOT NULL,
  `status` INT UNSIGNED NOT NULL,
  `flag` INT UNSIGNED NOT NULL,
  `title` VARCHAR(128) NOT NULL COMMENT '保留字段',
  `content_type` VARCHAR(64) NOT NULL,
  `type` VARCHAR(16) NOT NULL,
  `password` BINARY(80) NOT NULL,
  `expire_timestamp` BIGINT UNSIGNED NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `index_uuid` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandcastle`.`sandcastle_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandcastle`.`sandcastle_object` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `status` INT UNSIGNED NOT NULL,
  `sha512` BINARY(64) NOT NULL,
  `size` BIGINT NOT NULL,
  `path` VARCHAR(128) NOT NULL,
  `encrypt_key` BINARY(32) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
